export const COLOR_ACTIONS = {
INCREMENT: {
RED: "INCREMENT_RED",
 GREEN: "INCREMENT _GREEN", 
 BLUE: "INCREMENT _BLUE",
},
DECREMENT: {
RED: "DECREMENT _RED",
GREEN: "DECREMENT_GREEN",
BLUE: "DECREMENT _BLUE",
}
}